export const confessions = [
  {
    id: "1",
    campus: "University of Santo Tomas",
    text: "Crushed on my professor for the entire semester… never said a word. 😅",
    timestamp: "2025-05-27T15:22:00Z",
    likes: 42,
    comments: 5,
    user: "John Doe",
  },
  {
    id: "2",
    campus: "De La Salle University",
    text: "Skipped finals to watch Taylor Swift live. Zero regrets.",
    timestamp: "2025-05-26T11:15:00Z",
    likes: 67,
    comments: 10,
    user: "Jane Smith",
  },
  {
    id: "3",
    campus: "Ateneo de Manila University",
    text: "Accidentally called my prof 'mom' during recitation 😭",
    timestamp: "2025-05-25T08:40:00Z",
    likes: 130,
    comments: 20,
    user: "Jane Doe",
  },
  {
    id: "4",
    campus: "Polytechnic University of the Philippines",
    text: "Sold my thesis template for ₱2,000 and now 4 people are using it.",
    timestamp: "2025-05-24T17:00:00Z",
    likes: 89,
    comments: 7,
    user: "Bob Smith",
  },
  {
    id: "5",
    campus: "Far Eastern University",
    text: "Saw my crush crying in the hallway. Gave them a KitKat and ran away.",
    timestamp: "2025-05-24T12:30:00Z",
    likes: 54,
    comments: 3,
    user: "Alice Johnson",
  },
  {
    id: "6",
    campus: "University of the Philippines Diliman",
    text: "Was high during an oral exam and still got an A. What is life.",
    timestamp: "2025-05-23T09:10:00Z",
    likes: 115,
    comments: 12,
    user: "Charlie Brown",
  },
  {
    id: "7",
    campus: "Mapua University",
    text: "I pretend to understand Calculus so my classmates don’t panic.",
    timestamp: "2025-05-22T14:45:00Z",
    likes: 78,
    comments: 6,
    user: "Emily Davis",
  },
  {
    id: "8",
    campus: "San Beda University",
    text: "Met someone on the confession app… now they’re my girlfriend. ❤️",
    timestamp: "2025-05-21T18:00:00Z",
    likes: 143,
    comments: 25,
    user: "David Wilson",
  },
  {
    id: "9",
    campus: "Adamson University",
    text: "Still scared of our guard dog even after 4 years in college.",
    timestamp: "2025-05-20T16:10:00Z",
    likes: 32,
    comments: 0,
    user: "Grace Thompson",
  },
  {
    id: "10",
    campus: "National University",
    text: "Confessed to my crush… they ghosted me and now we’re thesis partners.",
    timestamp: "2025-05-19T10:05:00Z",
    likes: 97,
    comments: 14,
    user: "Michael Johnson",
  },
];
